final Map<String, String> enUS = {
  'appName': "Patchi Patchi",
  'patchi': "Patchi",
  'logIn': "Log In",
  'language': "Language",
  'aboutUs': "About Us",
  'contactUs': "Contact Us",
  'Legal': "Legal",
  'advertising': "Advertising",
  'signInToPatchiPatchi': "Sign In To Patchi Patchi",
  'signInWithGoogle': "Sign in with Google",
  'signInWithApple': "Sign in with Apple",
  'or': "or",
  'hintEmailOrPhone': "Email / Phone Number",
  'hintEmail': "Email",
  'login': "login",
  'forgotPassword': "Forget Password",
  'doNotHaveAnAccount': "Don’t have an account?",
  'signUp': "Sign up",
  'signIn': "Sign in",
  'createAccount': "Create Account",
  'alreadyHaveAnAccount': "Already have an account?",
  'password': "Password",
  'firstName': "First Name",
  'lastName': "Last Name",
  'email': "Email",
  'company': "Company",
  'street': "Street",
  'zip_code': "ZIP Code",
  'city': "City",
  'phoneNumber': "Phone Number",
  'passAdvise': "We advice use 8 or more characters with mix of letters, numbers and symbols",
  'patchi_sound': "[pach-ee pach-ee]",
  'patchi_desc': "Make Life Easier and Better \nby Patching.",
  'create_patchi': "CREATE YOUR PATCHI PATCHI",
  'photo_library': "Photo Library",
  'pattern_gallery': "Pattern Gallery",
  'favourites': "Favourites",
  'carousel': "Carousel",
  'exclusive': "Exclusive",
  'upload_own_photo': "UPLOAD YOUR OWN PHOTO",
  'cool_lockscreen_gift': "COOL LOCKSCREEN & FREE GIFT FROM:",
  'ad': "Ad",
  'pattern_gallery_desc': "PATTERN GALLERY FROM\nCOLLECTIONSTOCK",
  'patch_qr': "Patch QR",
  'add_qr': "Add Qr",
  'proceed': "Proceed",
  'create_qr': "Create New Qr Code",
  'scan': "Scan",
  'camera': "Camera",
  'personal': "Personal",
  'my_card': "My Card",
  'health_card': "Health Card",
  'others': "Others",
  'url': "Url",
  'instagram': "Instagram",
  'facebook': "Facebook",
  'youtube': "YouTube",
  'twitter': "Twitter",
  'linkedin': "Linkedin",
  'payme': "PayMe",
  'give_your_qr_name': "Give your QR a name",
  'qr_name': "Qr name",
  'customize': "Customize",
  'link': "Link",
  'payme_link': "Your PayMe Link",
  'insta_link': "Your Instagram Link",
  'fb_link': "Your Facebook Link",
  'youtube_link': "Your Youtube Link",
  'twitter_link': "Your Twitter Link",
  'linkedin_link': "Your Linkedin Link",
  'whatsapp_number': "Whatsapp Number",
  'number': "Number",
  'whatsapp_message': "Whatsapp Message",
  'message': "Message",
  'https': "https://",
  'add_logo': "Add Logo",
  'upload': "Upload",
  'scan_the_qr': "Scan The Qr",
  'add_personal_photo': "Add Personal Photo",
  'phoneNumber_work': "Phone (Work)",
  'phoneNumber_mobile': "Phone (Mobile)",
  'email_work': "Email (Work)",
  'email_personal': "Email (Personal)",
  'website': "Website",
  'id_pass': "ID Card / Passport No.",
  'd_o_b': "Date of Birth",
  'imp_notes': "Important Medical Notes",
  'allergies_reaction': "Allergies and Reactions",
  'blood_type': "Blood Type",
  'organ_donor': "Organ Donor",
  'weight_kg': "Weight (kg)",
  'height_cm': "Height (cm)",
  'select_blood': "Select Blood Type",
  'select_organ_donor': "Select Organ Donor",
  'select_weight_kg': "Select Weight (kg)",
  'select_height_cm': "Select Height (cm)",
  'emergency_contact_name': "Emergency Contact Name",
  'emergency_contact_number': "Emergency Contact Number",
  'medical_insurance_company': "Medical Insurance Company",
  'medical_insurance_number': "Medical Insurance Number / Policy",
  'all_like_your': "All your Likes and Downloads",
  'sign_in_to_view': "Sign In To View",
  'you_have_no_fav': "You have no Favourites yet",
  'descNewsLetter': "Yes, I would like to subscribe to the PATCHI PATCHI Newsletter and latest offers",
  'descPrivacyPolicy': "Yes, I accept the Patchi Patchi terms of use and privacy policy",
  'my_card_desc': "Create a QR Code that contains the contact details you wish to share. Once scanned, it can be saved instantly into the address book.",
  'health_card_desc': "Enter your personal health information and generate your health card. The QR code can only be scanned by professionals from authorized authorities in case of emergency.",
  'enterYourVerificationCode': "Enter Your\nVerification Code",
  'sentTo': "Sent to",
  'dummyEmail': "xxxxxx@gmail.com",
  'verify': "Verify",
  'reSend': "Resend",
  'enterYourEmail': "Enter Your Email",
  'sendCode': "Send Code",
  'newPassword': "New Password",
  'resetPassword': "Reset Password",
  'carousel_desc_1': "Change your lockscreen automatically every day",
  'carousel_desc_2': "Based on your style settings and QR patching selection",
  'activate_carousel': "Activate Carousel",
  'your_carousel': "Your Carousel",
  'activate_carousel_desc': "Select 1-5 styles for your lockscreens",
  'sound_enable': "Sound Enable",
  'status': "Status",
  'done': "Done",
  'more': "More",
  'less': "Less",
  'activated': "Activated",
  'activate': "Activate",
  'exclusive_desc': "Scan the QR of your\nfavourite brand or shop to get their\nnexclusive lockscreen",
  'myAccount': "My Account",
  'userInformation': "User Information",
  'qrZoneAndNotPatchQR': "QR Zone",
  'giftScanner': "Gift Scanner",
  'phone': "Phone",
  'currentPassword': "Current Password",
  'confirmNewPassword': "Confirm New Password",
  'legal': "Legal",
  'termOfUse': "Term of Use",
  'privacyPolicy': "Privacy Policy",
  'scanAgain': "Scan Again",
  'free': "Free",
  'from': "From",
  'scanSuccessful': "Scan Successful",
  'expiresIn': "Expires In",
  'campaignExpired': "Campaign Expired",
  'qrUsedAlready': "Qr Used Already",
  'patchQr': "Patch Qr",
  'descPatchQr': "Check out the different arrangement of patching QR codes on your lockscreen. No more than 5 QR codes can be patched.",
  'lockScreenGuide': "Lockscreen Guide",
  'descLockScreen': "For IOS, lockscreens will need to be set manually.\n\nOnce a Patchi Patchi has been created and saved to your photo library, go to Settings > Wallpapers to select and save it as the lockscreen for your device.",
  'upload_img_desc_1': "Enter the PIN to get this exclusive lockscreen from:",
  'upload_img_desc_2': "Check with the brand on how to collect your PIN",
  'free_gift': "Free Gift",
  'image': "Image",
  'scanning': "Scanning...",
  'qr_not_found': "QR Not Found",
  'lockScreenChange': "Lockscreen Changed Successfully",
  'deactivated_Desc': "By selecting this\nlockscreen, your\nCarousel will be\nautomatically\ndeactivated ",
  'free_gift_desc': "Get this unique gift by patching the Gift QR code to the branded lockscreen and by presenting the code for scanning.",
  'title_1': "the magic of patching",
  'sub_title_1': "Create lockscreens for your mobile or tablet and patch them with any kind of QR code.",
  'title_2': "make life better & easier",
  'sub_title_2': "Without unlocking your device, share personal or social contact details, give restricted access to your health status, use loyalty QR codes instantly and get scanned directly to receive payments.",
  'title_3': "exclusive lockscreens",
  'sub_title_3': "Patch QR on the coolest & most exclusive lockscreens from famous brands.",
  'title_4': "gift hunting",
  'sub_title_4': "Hunt down the branded lockscreens that will reward you with a special gift.",
  'start_now': "Start Now",
  'msgLoginFail':"Login fail please try again!",
  'msgLoginSuccess':"Login Successful",
  'errMessageEmail': "Please Enter Valid Email Address",
  'errMessagePassword': "Please Enter Password Must be grater than 8 character",
  'errMessageEnterPassword': "Please Enter Valid Password",
  'noInternetConnection': "No Internet Connection",
  'descNoInternetConnection': "It seems that you are not connected to the Internet. Kindly check your network settings.",
  'cancel': "cancel",
  'retry': "Retry",
  'errMessageFirstName': "Please enter your first name",
  'errMessageLastName': "Please enter your last name",
  'errMessagePhone': "Please enter your phone number",
  'errMessageCheckNewsletter': "Please check newsletter and offers",
  'errMessageCheckTerms': "Please check terms of use and privacy policy",
  'msgSignupSuccess': "Register Successful",
  'msgSignupFail': "Register fail please try again!",
  'msgVerifyCreateAccountSuccess': "Create account verify successfully",
  'msgVerifyCreateAccountFail': "Create account verify fail",
  'errMessagePinIsInvalid': "Please enter valid pin",
  'msgResendCodeSuccess': "Code send your mail successfully",
  'msgResendCodeFail': "Code send your mail fail, please try again",
  'msgResetPasswordSuccess': "Password Changed successfully",
  'msgResetPasswordFail': "You password is not changed, please try again",
  'msgLogoutSuccess': "Logout successfully",
  'msgLogoutFail': "Logout fail, please try again",
  'msgUpdateDetailsSuccess': "Data update successfully",
  'msgUpdateDetailsFail': "Data update fail, please try again",
  'msgUpdatePasswordSuccess': "Password update successfully",
  'msgUpdatePasswordFail': "Password update fail, please try again",
  'errMessageCurrentPassword': "Please Enter Valid Current Password",
  'errMessageNewPassword': "Please Enter Valid New Password",
  'errPasswordMustBeSame': "Confirm password must be same as new password",
  'errMessageEnterQrName': "QR name has not been given",
  'errMessageEnterLink': "Please Enter Valid Url",
  'errMessageEnterInstaLink': "Please Enter Valid Instagram Url",
  'errMessageEnterFacebookLink': "Please Enter Valid Facebook Url",
  'errMessageEnterYouTubeLink': "Please Enter Valid YouTube Url",
  'errMessageEnterTwitterLink': "Please Enter Valid Twitter Url",
  'errMessageEnterLinkedinLink': "Please Enter Valid Linkedin Url",
  'errMessageEnterWhatsappLink': "Please Enter Valid Whatsapp Message",
  'errMessageEnterWhatsappNumber': "Please Enter Valid Whatsapp Number",
  'getInTouch': "Get in touch!",
  'aboutPatchiPatchi': "About Patchi Patchi",
  'premium': "Premium",
  'premium_1_desc': "Patch up to 5 QR codes on your lock screen.",
  'premium_2_desc': "Replace PATCHI PATCHI with your company logo / an emoji… ANYTHING!",
  'premium_3_desc': "View and redeem gift offers 24 hours ahead!",
  'premium_4_desc': "Create HEALTH PRO QR to share your health status with professionals in case of emergency.",
  'premium_4_1_desc': "Create",
  'premium_4_2_desc': " HEALTH PRO ",
  'premium_4_3_desc': "QR to share your health status with professionals in case of emergency.",
  'premium_5_desc': "Access to limited edition lock screens created by famous artist.",
  'premium_6_desc': "Receive one notification per week to redeem a valuable gift without hunting.",
  'best_deal': "Best Deal",
  'most_popular': "Most Popular",
  'months': "Months",
  'month': "Month",
  'hk488.00': "HK\$488.00",
  'hk248.00': "HK\$248.00",
  'hk48.00': "HK\$48.00",
  'save_two_month': "Save 2 Months",
  'save_one_month': "Save 1 Months",
  'subscribe_now': "Subscribe Now",
  'no_thanks': "No Thanks",
  'select': "Select",
  'qrInvalid': "Qr Invalid",
  'save': "Save",
  'select_one_qr': "Please select at least one QR.",
  'select_one_carousel': "Please select at least one Carousel.",
  'home': "Home",
  'notification_title': "Patchi Patchi",
  'notification_msg': "Cool LockScreen & Free Gift From Louis Vuitton",
  'chatWithUsNow': "Chat With Us Now",
  'delete_success': "QR Delete Successfully",
  'created_success': "QR Create Successfully",
  'update_success': "Update Successfully",
  'whatsapp_not_installed': "whatsapp not installed",
  'fill_other_field': "Please fill at list one other field",
  'deactivated': "deactivated",
  'whatsapp': "Whatsapp",
  'patchQrScreen': "Patch Qr Screen",
  //<<---------------------************* All Popups given by the client *************--------------------->>
  'popup_verification_failed' : "Verification failed. Enter new code",
  'popup_enter_name_for_qr' : "Enter a name for the QR",
  'popup_use_diff_name' : "Use different name",
  'popup_enter_valid_url' : "Enter valid URL",
  'popup_this_email_not_registered' : "This email is not registered",
  'popup_pass_incorrect' : "The password is incorrect",
  'popup_code_resent' : "Code resent",
  'popup_login_success' : "Log in successful",
  'popup_enter_valid_email' : "Enter a valid Email",
  'popup_enter_valid_no' : "Enter a valid number",
  'popup_fill_all_fields' : "Fill in all the fields",
  'popup_accept_terms_and_privacy_policy_proceed' : "Accept Terms & Privacy Policy to proceed",
  'popup_please_enter_new_password' : "Please enter a new password",
  'popup_please_enter_verification_code' : "Please enter the verification code",
  'popup_password_changed' : "Password changed",
  'popup_the_current_new_password_cannot_be_the_same' : "The current and new password cannot be the same",
  'popup_your_password_and_confirmation_password_does_not_match' : "Your password and confirmation password does not match",
  'popup_lockscreen_changed_successfully' : "Lockscreen changed successfully",
  'popup_lockscreen_saved_to_photo_library' : "Lockscreen saved to photo library",
  'popup_this_phone_number_is_not_registered' : "This phone number is not registered",
  'popup_to_use_this_function,_make_sure_that_this_email_is_registered_at_patchi_patchi' : "To use this function, make sure that this email is registered at Patchi Patchi.",
  'popup_payment_verification_failed' : "Payment verification failed",
  'popup_billing_address_updated' : "Billing address Updated",
  'popup_thank_you_for_subscribing' : "Thank you for subscribing",
  'popup_unsubscribed_successfully' : "Unsubscribed successfully",
  'popup_premium_plan_activated' : "Premium Plan Activated",
  'gift' : "Gift",
  'enter a url' : "Enter a url",
};
