services:
  fhir-db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_DB: fhirdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - fhir-db-data:/var/lib/postgresql/data
    networks:
      - fhir-network

  keycloak-db:
    image: postgres:13
    container_name: keycloak-db
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloakpassword
    volumes:
      - keycloak-db-data:/var/lib/postgresql/data
    networks:
      - fhir-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@domain.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - ${PG_ADMIN_CLIENT_PORT}:80
    networks:
      - fhir-network

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    container_name: keycloak
    depends_on:
      - keycloak-db
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloak-db
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloakpassword
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - ./pa-realm-export.json:/opt/keycloak/data/import/keycloak-realm.json:ro
      - ./keycloak-extensions:/opt/keycloak/providers:ro
      - ./custom-theme:/opt/keycloak/themes/custom-theme:ro  
    command: ["start-dev", "--import-realm"]
    ports:
      - ${KC_PORT}:${KC_PORT}
    networks:
      - fhir-network

  hapi-fhir:
    build: ../  
    container_name: hapi-fhir
    environment:
       SERVER_PORT: ${FHIR_SERVER_PORT}
       server.serverAddress: ${FHIR_ADDRESS_TARGET}/fhir/ 
       JAVA_TOOL_OPTIONS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
       SPRING_DATASOURCE_URL: jdbc:postgresql://fhir-db:5432/fhirdb
       SPRING_DATASOURCE_USERNAME: admin
       SPRING_DATASOURCE_PASSWORD: password
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_SERVER-URI: ${KC_ADDRESS_TARGET}
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ISSUER-URI: ${KC_ADDRESS_TARGET}/realms/physical_activity
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ADMIN-BASE-URI: ${KC_ADDRESS_TARGET}/admin/realms/       
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_BASE-URI: ${KC_ADDRESS_TARGET}/realms/
       SPRING_SECURITY_OAUTH2_CLIENT_RESOURCESERVER_JWT_ISSUER-URI: ${KC_ADDRESS_TARGET}/realms/physical_activity
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ADMIN-USERNAME: ${KC_ADMIN_USER}
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_ADMIN-PASSWORD: ${KC_ADMIN_PASSWORD}
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_FHIR-ADMIN-USERNAME: ${KC_FHIR_ADMIN_USER}
       SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_KEYCLOAK_FHIR-ADMIN-PASSWORD: ${KC_FHIR_ADMIN_PASSWORD}
    depends_on:
     - fhir-db
     - keycloak
    ports:
     - ${FHIR_SERVER_PORT}:${FHIR_SERVER_PORT}
     - 5005:5005
    networks:
     - fhir-network            

volumes:
  fhir-db-data:
  keycloak-db-data:

networks:
  fhir-network:
    driver: bridge 